### PR TITLE
YSHOP2-329: [Features collections] Padding bottom does not seems to work

### PR DESCRIPTION
**Pull request by adildev101**
## JIRA Ticket

[YSHOP2-329](https://youcanshop.atlassian.net/browse/YSHOP2-329)

## QA Steps

- [ ] `pnpm i`
- [ ] `pnpm dev`

## Note

Leave empty when you have nothing to say

[YSHOP2-329]: https://youcanshop.atlassian.net/browse/YSHOP2-329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by bj-anas — COMMENTED** [review]
I guess removing the setting option isn't a good idea. If you look at the COD v3 we have this option of space top and space bottom.
Screen Shot 2023-04-12 at 11 53 50

**Review by bj-anas — COMMENTED** [review]
I have checked COD v2 and I see that they use padding top and padding bottom. please try to unify the settings in all COD theme versions
Screen Shot 2023-04-12 at 11 58 25

**Comment by adildev101** [comment]
we already have it also on this version just a different on the naming, on cod theme v3 i name it space top or bottom and hire we have margin top or bottom

**Comment by adildev101** [comment]
we don't rely on other themes settings hire on COD 1 we use padding or margin for the space naming.
so where is the problem ?

**Pull request merged**
